# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 54592c082fe47c705345ca34e550a8d5edc8d3cc52c2e72a2e5e53ec890f0a4b35690c14d3bbfab05925fef1f02ba45953b321eaf6aee431c63536a1450c564c

test:
  secret_key_base: ce18113533f830671156ed4dc0dd7028fdafd9c40725ff6a6356c7bd08f671f84e55e5ae1857bbc8bbd182832663bca45a7550a4910cc620346cdd13b0c16b2e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
